# Generated by Django 2.0.6 on 2018-06-24 05:07

from django.db import migrations, models
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='category',
            field=models.ForeignKey(on_delete=True, to='menu.MenuItemCategory', verbose_name='category'),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='parent',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=True, related_name='children', to='menu.MenuItem', verbose_name='parent menu item'),
        ),
    ]
